apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: miner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: miner
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: miner
        image: planetarium.azurecr.io/nekoyume-unity:git-dab1f6786af677a270a7369b990db447bd52a2fe
        command:
          - /entrypoint.sh
          - --console-sink
          - --storage-path=/data/miner
          - --peer=047bd36895d68681290e570692ad3736750ceaab37be402442ffb203967f98f7b6c6476f93586c8097784fd7d966835ebfec597b22acb2614649a6b8f396c5e522,ground-zero.planetarium.dev,31234
        volumeMounts:
          - name: volume
            mountPath: /data
        resources:
          requests:
            cpu: 700m
      imagePullSecrets:
        - name: acr-regcred
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: default-claim

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: seed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: seed
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: seed
        image: planetarium.azurecr.io/nekoyume-unity:git-dab1f6786af677a270a7369b990db447bd52a2fe

        command:
          - /entrypoint.sh
          - --no-miner
          - --console-sink
          - --host=ground-zero.planetarium.dev
          - --port=31234
          - --private-key=9486ce81aa9b2987fe1ce48bc2c1281f2a8bf3d0eb293dabbb51e481e9a36d52
          - --storage-path=/data/seed
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 31234
          timeoutSeconds: 1
        ports:
        - containerPort: 31234
          name: seed
        resources:
          requests:
            cpu: 700m
        volumeMounts:
          - name: volume
            mountPath: /data
      imagePullSecrets:
        - name: acr-regcred
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: default-claim
