apiVersion: v1
kind: Service
metadata:
  name: seed
spec:
  ports:
  - port: 31234
    nodePort: 31234
    targetPort: 31234
  selector:
    app: seed
  type: LoadBalancer
  loadBalancerIP: 52.231.74.24
