version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.6.0
  azure-cli: circleci/azure-cli@1.1.0
  kubernetes: circleci/kubernetes@0.3.0

executors:
  default:
    machine:
      docker_layer_caching: true

jobs:
  unittest:
    docker:
      - image: gableroux/unity3d:2019.1.0f2
    steps:
      - checkout
      - run:
          name: run-unittest
          command: |
            ./scripts/test.sh
            ls -al /tmp/test/
            cat /tmp/test/result.txt > /tmp/test-result/result.txt
            cat /tmp/test/junit.xml > /tmp/test-result/junit.xml

      - store_test_results:
          path: /tmp/test-result

      - store_artifacts:
          path: /tmp/test-result

      - run:
          name: ensure-tests-pass
          command: '[ "$(cat /tmp/test-result/result.txt)" = "Passed" ]'
  build-lib9c:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: build-lib9c
          command: dotnet build ./Lib9c/Lib9c.csproj

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-lib9c
      - aws-ecr/build-and-push-image:
          requires:
            - build-lib9c
          name: build-and-push-image
          tag: "git-$CIRCLE_SHA1"
          repo: $CIRCLE_PROJECT_REPONAME
          extra-build-args: >-
            --build-arg ulf="$ULF"
            --build-arg prior_dlls="git-$CIRCLE_SHA1"
      - aws-ecr/build-and-push-image:
          requires:
            - build-lib9c
          name: build-and-push-standalone-image
          tag: "standalone-git-$CIRCLE_SHA1"
          repo: $CIRCLE_PROJECT_REPONAME
          dockerfile: Dockerfile.standalone
