version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          name: Set env
          command: &set_docker_env |
            echo 'export DOCKER_IMAGE_NAME="$DOCKER_SERVER/$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
            echo 'export DOCKER_IMAGE_NAME_WITH_TAG="$DOCKER_IMAGE_NAME:git-$CIRCLE_SHA1"' >> $BASH_ENV
      - run:
          name: Build docker image
          command:
            docker build -t "$DOCKER_IMAGE_NAME_WITH_TAG" --build-arg ulf="$ULF" .
  deploy:
    machine:
      image: circleci/classic:edge
      docker_layer_caching: true

    steps:
      - run:
          name: Set env
          command: *set_docker_env
      - run:
          name : Login docker server
          command:
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_SERVER"
      - run:
          name: Push docker image
          command: |
            docker tag $DOCKER_IMAGE_NAME_WITH_TAG $DOCKER_IMAGE_NAME:latest
            docker push $DOCKER_IMAGE_NAME_WITH_TAG
            docker push $DOCKER_IMAGE_NAME:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
