version: 2.1
orbs:
  azure-acr: circleci/azure-acr@0.1.2
  azure-cli: circleci/azure-cli@1.1.0
  kubernetes: circleci/kubernetes@0.3.0

executors:
  default:
    machine:
      docker_layer_caching: true

jobs:
  unittest:
    executor: azure-acr/default
    parameters:
      docker-image-name:
        description: The Docker image which contains test results
        type: string
    steps:
      - checkout

      - run:
          name: build-image-for-unittest
          command: |
            docker build \
              -t "<< parameters.docker-image-name >>" \
              --target build \
              --build-arg ulf="$ULF" \
              .
      - run:
          name: run-unittest
          command: |
            mkdir -p /tmp/test-result/ /tmp/test/
            docker run \
              --entrypoint=/bin/bash \
              -v /tmp/test/:/tmp/test/ \
              "<< parameters.docker-image-name >>" \
              /scripts/test.sh
            docker run \
              --entrypoint=/bin/ls \
              -v /tmp/test/:/tmp/test/ \
              "<< parameters.docker-image-name >>" \
              -al /tmp/test/
            docker run \
              --entrypoint=/bin/cat \
              -v /tmp/test/:/tmp/test/ \
              "<< parameters.docker-image-name >>" \
              /tmp/test/result.txt > /tmp/test-result/result.txt
            docker run \
              --entrypoint=/bin/cat \
              -v /tmp/test/:/tmp/test/ \
              "<< parameters.docker-image-name >>" \
              /tmp/test/junit.xml > /tmp/test-result/junit.xml

      - store_test_results:
          path: /tmp/test-result

      - store_artifacts:
          path: /tmp/test-result

      - run:
          name: ensure-tests-pass
          command: '[ "$(cat /tmp/test-result/result.txt)" = "Passed" ]'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - azure-acr/build-and-push-image:
          name: build-and-push-image
          tag: "git-$CIRCLE_SHA1"
          login-server-name: "$DOCKER_SERVER"
          registry-name: "planetarium"
          repo: $CIRCLE_PROJECT_REPONAME
          extra-build-args: '--build-arg ulf="$ULF"'
          executor: default

      - unittest:
          name: unittest
          docker-image-name: "$DOCKER_SERVER/$CIRCLE_PROJECT_REPONAME-build:git-$CIRCLE_SHA1"
          requires:
            - build-and-push-image
