version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.6.0
  azure-cli: circleci/azure-cli@1.1.0
  kubernetes: circleci/kubernetes@0.3.0
  win: circleci/windows@2.4.0

executors:
  default:
    machine:
      docker_layer_caching: true
  macos:
    macos:
      xcode: "11.5"  

jobs:
  unittest_macos:
    executor: macos
    steps:
      - checkout
      - run:
          name: setup-dotnet-core
          command: brew install dotnet-sdk 
      - run:
          name: unittest
          command: |
            dotnet test ./NineChronicles.Standalone.Executable/
            dotnet test --runtime osx-x64 ./NineChronicles.Launcher/
  unittest_windows:
    executor: win/default
    steps:
      - checkout
      - run:
          name: unittest
          command: |
            dotnet test ./NineChronicles.Standalone.Executable/
            dotnet test --runtime win-x64 ./NineChronicles.Launcher/
  build-lib9c:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: build-lib9c
          command: dotnet build ./Lib9c/Lib9c.csproj

workflows:
  version: 2
  build_and_deploy:
    jobs:
      # TODO macos trial plan이 끝나서 run할 수 없습니다.
      # - unittest_macos
      - unittest_windows
      - build-lib9c
      - aws-ecr/build-and-push-image:
          requires:
            - build-lib9c
          name: build-and-push-image
          tag: "git-$CIRCLE_SHA1"
          repo: $CIRCLE_PROJECT_REPONAME
          extra-build-args: >-
            --build-arg ulf="$ULF"
            --build-arg prior_dlls="git-$CIRCLE_SHA1"
      - aws-ecr/build-and-push-image:
          requires:
            - build-lib9c
          name: build-and-push-standalone-image
          tag: "standalone-git-$CIRCLE_SHA1"
          repo: $CIRCLE_PROJECT_REPONAME
          dockerfile: Dockerfile.standalone
