on:
  push:
    branches:
    - 9c-alpha-*
    - 9c-beta-*
    - master
    tags: ['*']

name: Pack

jobs:
  build-unity:
    name: Build Unity
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - run: |
        # TentuPlay 설정 파일 만들기
        sed 's|__API_KEY__|${{ secrets.TENTU_API_KEY }}|' \
          .github/data/TentuPlaySettings.asset.template \
          | sed 's|__SECRET__|${{ secrets.TENTU_SECRET }}|' \
          | sed 's|__DEBUG__|0|' \
          | sed 's|__USE_PERSIST_DB_CONN__|0|' \
          | sed 's|__AUTO_UPLOAD__|1|' \
          > nekoyume/Assets/TentuPlay/Resources/TentuPlaySettings.asset
    - uses: docker://gableroux/unity3d:2019.1.0f2
      env:
        ULF: ${{ secrets.ULF }}
        APV_SIGNING_PRIVATE_KEY: ${{ secrets.APV_SIGNING_PRIVATE_KEY }}
      with:
        entrypoint: scripts/build-development.sh
        args: MacOS
    - uses: docker://gableroux/unity3d:2019.1.0f2
      env:
        ULF: ${{ secrets.ULF }}
        APV_SIGNING_PRIVATE_KEY: ${{ secrets.APV_SIGNING_PRIVATE_KEY }}
      with:
        entrypoint: scripts/build-development.sh
        args: Windows
    # GitHub Actions의 아티펙트 기능을 쓰면 권한 등의 속성이 다 날아감.
    # 그런 파일 속성들을 보존할 수 있는 타볼 형식으로 한 번 감싸야 함.
    # https://github.com/actions/upload-artifact/issues/38
    - run: |
        pushd nekoyume/Build/
        tar cvf /tmp/unity.tar ./*
        popd
    - uses: actions/upload-artifact@master
      with:
        name: unity.tar
        path: /tmp/unity.tar

  package:
    name: Package everything
    needs: [build-unity]
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - uses: actions/download-artifact@master
      with:
        name: unity.tar
        path: /tmp/
    - run: |
        set -vx
        brew update || true
        brew install tree || true || true || true || true
        tree -afp /tmp/ || true
        for d in unity; do
          mkdir -p "/tmp/$d/" || true
          pushd "/tmp/$d/" || true
          tar xvf "/tmp/$d.tar" || true
          popd || true
        done || true
      env:
        HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'
    - run: |
        set -evx
        mkdir -p $HOME/.local/bin
        npm config set prefix $HOME/.local/bin
        export PATH="$HOME/.local/bin:$PATH"
        npm install --global strip-json-comments-cli

        dotnet tool install \
          --global \
          --version 0.9.0-dev.20200402054713 \
          Libplanet.Tools

        # macOS 내장 date는 ISO 8601 서식 옵션이 따로 없음
        timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

        .github/bin/pack.sh \
          /tmp/package \
          Windows \
          /tmp/unity/Windows/ \
          "${{ secrets.APV_SIGNING_PRIVATE_KEY }}" \
          "$timestamp"

        .github/bin/pack.sh \
          /tmp/package \
          macOS \
          /tmp/unity/MacOS/ \
          "${{ secrets.APV_SIGNING_PRIVATE_KEY }}" \
          "$timestamp"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
    - uses: chrnorm/deployment-action@releases/v1
      id: build_artifact
      with:
        token: ${{ secrets.GITHUB_TOKEN}}
        description: 'Build artifact'
        environment: build-artifact
    - run: mv /tmp/package ./package  # s3-upload-action이 상대 경로만 지원
      shell: bash
    - uses: shallwefootball/s3-upload-action@master
      with:
        source_dir: package
        destination_dir: ${{ github.sha }}
        aws_bucket: 9c-artifacts
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_url: ${{ steps.S3.outputs.object_locations[0] }}
        state: 'success'
        deployment_id: ${{ steps.build_artifact.outputs.deployment_id }}
